[Addon]
Name=clarityime
Category=InputMethod
Version=0.3.0
Library=clarityime
Type=SharedLibrary
OnDemand=True
Authors=Lumen
Comment=ClarityIME voice clarify input method
Comment[zh_CN]=ClarityIME 语音清晰化输入法
